/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;
/* Header for class com_noobs_noobshackathon_OpenCvNativeClass */

#ifndef _Included_com_noobs_noobshackathon_OpenCvNativeClass
#define _Included_com_noobs_noobshackathon_OpenCvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_noobs_noobshackathon_OpenCvNativeClass
 * Method:    imgProcess
 * Signature: (J)I
 */
void toGray(Mat src,Mat& dst);
JNIEXPORT void JNICALL Java_com_noobs_noobshackathon_OpenCvNativeClass_imgProcess
(JNIEnv *, jclass, jlong matArrSrc, jlong matArrDst);

#ifdef __cplusplus
}
#endif
#endif
